### ISSUE TITLE
跑不起来？尝试谷歌了但是仍然没解决。

### ISSUE THREAD

**Issue by xieyezi** [xuexiangjys/FlutterSample#1]
执行安装依赖命令：` flutter packages get`
报错如图：
<img width="1011" alt="QQ20200309-123027@2x" src="https://user-images.githubusercontent.com/16821989/76182988-cb171b80-6201-11ea-92ce-5b9900827fbb.png">

**Comment by xuexiangjys** [comment]
`flutter packages get`命令是下载依赖包的命令,你依赖包下不下来是你网络的问题,懂?

**Comment by xieyezi** [comment]
我就是不懂才问的呀？明显不是网络问题好吧

**Comment by xieyezi** [comment]
你这语气，好盛气凌人啊

**Comment by xuexiangjys** [comment]
> 你这语气，好盛气凌人啊

首先,你的提问的语气就很有问题.issue不是给你来抱怨问题的,既然我开源了,最基本的跑是肯定没问题的.
其次,我不想在这里跟你浪费时间,自己去插件平台看吧: https://pub.dev/packages/intl
最后,我不是你的保姆,没有义务伺候你.

**Comment by xieyezi** [comment]
是是是，我不该问你，不该打扰你，我错了，好吧😓
